/**
 * DocumentTexture — the full-page background.
 *
 * A warm dark base with a very subtle, CSS-only paper-grain overlay (~3%
 * opacity, generated by an inline SVG feTurbulence so there are no image
 * assets, gradients, particles, or mesh blobs). The intent is dim
 * reading-room lighting, not a tech demo: the grain should be felt more
 * than seen.
 */

// Fine film grain as a tileable SVG data URI. baseFrequency tuned high for a
// tight, papery grain rather than coarse blotches.
const GRAIN =
  "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='160' height='160'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='2' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E\")";

export default function DocumentTexture() {
  return (
    <div aria-hidden className="pointer-events-none fixed inset-0 -z-10 bg-ink">
      <div
        className="absolute inset-0"
        style={{
          backgroundImage: GRAIN,
          backgroundRepeat: "repeat",
          backgroundSize: "160px 160px",
          opacity: 0.03,
          // Keep the grain neutral against the warm ground.
          mixBlendMode: "overlay",
        }}
      />
    </div>
  );
}
