"""Judge agent: a supervisory layer that adjudicates the forecast.

The analyst and forecast agents can each be individually plausible yet jointly
incoherent — e.g. the analyst reads bullish technicals while the forecaster
predicts a decline. Acting on contradictory signals is how automated systems
lose money. The judge exists to catch that: it scores the *agreement* between
the descriptive and predictive views, raises risk flags, and renders an
auditable verdict (Approved / Conflicted / Rejected) before anything downstream
acts on the call.

The override reasoning is generated by a Groq-hosted LLM so the audit log
carries a plain-English justification. The call is best-effort: if no API key
is configured or the request fails, we fall back to a deterministic summary so
the pipeline never blocks on an external dependency.
"""

from __future__ import annotations

import logging
import os
import re
import uuid

from backend.ml.models.forecaster import NEUTRAL_BAND
from backend.schemas import (
    AnalystReport,
    ForecastReport,
    JudgeVerdict,
    Verdict,
)

logger = logging.getLogger(__name__)

# A confidence interval wider than this fraction of the [0,1] probability space
# means the two boosters disagree materially — the forecast is not trustworthy.
WIDE_CI_THRESHOLD = 0.3

# Verdict thresholds on the consistency score.
APPROVE_MIN_CONSISTENCY = 0.7
REJECT_MAX_CONSISTENCY = 0.3

GROQ_MODEL = "llama-3.3-70b-versatile"

# The judge adjudicates *internal coherence*, not market correctness. The LLM
# must never imply the forecast is right — it can only describe agreement
# between the two agents and the model's own self-reported uncertainty. This
# prompt hard-constrains the vocabulary to keep the audit log defensible.
GROQ_SYSTEM_PROMPT = (
    "You are a risk-governance judge for an automated equity-analysis system. "
    "You write concise, defensible audit justifications.\n\n"
    "CRITICAL CONSTRAINTS:\n"
    "- You assess ONLY the internal coherence of two software agents: the "
    "analyst agent (which summarises current technical/fundamental signals) and "
    "the forecast agent (which outputs a directional probability). You are NOT "
    "evaluating whether any prediction is or will be true.\n"
    "- The consistency score measures ONLY how much the two agents' signals AGREE "
    "with each other. A high score means they point the same way; it does NOT "
    "mean the forecast is right.\n"
    "- Flags describe ONLY model-internal confidence / data-quality conditions "
    "(e.g. wide confidence interval, near-coin-flip probability), NOT real-world "
    "outcomes.\n"
    "- NEVER claim or imply predictive accuracy, correctness, or real-world "
    "reliability. Do NOT use the words 'accurate', 'accuracy', 'correct', "
    "'reliable', 'reliable performance', 'right', 'proven', or 'validated', nor "
    "any synonym that suggests the prediction will hold true.\n"
    "- Frame everything as agreement/disagreement between agents and as "
    "model-reported confidence. Describe what was measured, not what will happen."
)

# Post-generation guardrail. The system prompt *asks* the LLM to avoid claiming
# predictive correctness, but a prompt is not a guarantee — so we also *verify*
# the output. Any of these stems implies the forecast is correct or will hold
# true, which the judge must never assert. Matched as stems (case-insensitive)
# so inflections are caught too: 'accura' -> accurate/accuracy/accurately,
# 'reliab' -> reliable/reliably/reliability, 'validat' -> validate/validated.
_BANNED_VOCABULARY = (
    "accura",
    "correct",
    "reliab",
    "proven",
    "validat",
    "right",
)
_BANNED_PATTERN = re.compile(
    r"\b(?:" + "|".join(_BANNED_VOCABULARY) + r")\w*", re.IGNORECASE
)


def _banned_terms_in(text: str) -> list[str]:
    """Return any banned-vocabulary matches found in ``text`` (empty if clean)."""
    return [m.group(0) for m in _BANNED_PATTERN.finditer(text)]


def _analyst_composite_prob(report: AnalystReport) -> float:
    """Collapse the analyst's technical read into a single bullishness score.

    The analyst report has no scalar verdict of its own, so we synthesise one
    from three orthogonal momentum/positioning signals, each normalised to
    [-1, 1] and averaged, then mapped to a probability-like [0, 1]:

      * RSI relative to its 50 midpoint (momentum),
      * MACD histogram sign (trend acceleration),
      * %B position within the Bollinger envelope (mean-reversion context).

    Expressing it on the same [0, 1] scale as the forecaster's ``probability_up``
    lets us compare the two views directly.
    """
    tech = report.technicals

    rsi_signal = max(-1.0, min(1.0, (tech.rsi - 50.0) / 50.0))
    macd_signal = 1.0 if tech.macd_hist > 0 else (-1.0 if tech.macd_hist < 0 else 0.0)
    bb_signal = max(-1.0, min(1.0, (tech.bb_pct - 0.5) * 2.0))

    composite = (rsi_signal + macd_signal + bb_signal) / 3.0  # [-1, 1]
    return (composite + 1.0) / 2.0  # [0, 1]


def _compute_consistency(analyst_prob_up: float, forecast_prob_up: float) -> float:
    """Score how well the analyst and forecast directions agree, in [0, 1].

    Both views live on a shared P(up) scale, so their absolute difference is a
    natural disagreement metric: identical convictions score 1.0, opposite
    convictions (0 vs 1) score 0.0. This rewards directional agreement while
    still penalising magnitude gaps between a weak and a strong call.
    """
    return 1.0 - abs(analyst_prob_up - forecast_prob_up)


def _collect_flags(forecast: ForecastReport) -> list[str]:
    """Raise qualitative risk flags from the forecast's own uncertainty signals."""
    flags: list[str] = []

    ci_low, ci_high = forecast.confidence_interval
    if (ci_high - ci_low) > WIDE_CI_THRESHOLD:
        flags.append("wide uncertainty")

    # Headline probability sitting inside the neutral band means the model is
    # effectively undecided — a coin-flip dressed up as a directional call.
    if abs(forecast.direction_probability - 0.5) <= NEUTRAL_BAND:
        flags.append("low confidence")

    return flags


def _decide_verdict(consistency_score: float, flags: list[str]) -> Verdict:
    """Map the consistency score and flags onto the three-state verdict.

    Approval demands both high agreement *and* a clean flag sheet; a strong
    consistency score cannot rescue a forecast the model itself flagged as
    uncertain. Low agreement is an outright rejection; everything in between is
    escalated as Conflicted for human review.
    """
    if consistency_score < REJECT_MAX_CONSISTENCY:
        return Verdict.REJECTED
    if consistency_score > APPROVE_MIN_CONSISTENCY and not flags:
        return Verdict.APPROVED
    return Verdict.CONFLICTED


def _fallback_reasoning(
    verdict: Verdict, consistency_score: float, flags: list[str]
) -> str:
    """Deterministic justification used when the LLM call is unavailable."""
    flag_text = ", ".join(flags) if flags else "no risk flags"
    return (
        f"Verdict {verdict.value} was assigned because the analyst and forecast "
        f"directions agree at a consistency of {consistency_score:.2f}, with "
        f"{flag_text}. This decision was generated without the LLM justifier "
        f"(Groq unavailable), so it reflects the rule thresholds directly."
    )


def _generate_override_reasoning(
    verdict: Verdict, consistency_score: float, flags: list[str]
) -> str:
    """Ask a Groq-hosted LLM to justify the verdict in 2-3 plain-English sentences.

    Falls back to a deterministic summary when ``GROQ_API_KEY`` is unset or the
    API call fails, so adjudication never depends on network availability.
    """
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        logger.info("GROQ_API_KEY not set; using deterministic override reasoning.")
        return _fallback_reasoning(verdict, consistency_score, flags)

    flag_text = ", ".join(flags) if flags else "none"
    prompt = (
        "Justify the verdict below for a compliance audit log in 2-3 plain-English "
        "sentences. Reference the numbers.\n\n"
        f"Verdict: {verdict.value}\n"
        f"Consistency score: {consistency_score:.2f} — measures only how closely the "
        "analyst agent's signals and the forecast agent's directional call AGREE with "
        "each other (1.0 = identical direction, 0.0 = opposite). It says nothing about "
        "whether the prediction will come true.\n"
        f"Risk flags: {flag_text} — these are confidence / data-quality signals derived "
        "from the model's own internal uncertainty (e.g. wide confidence interval, "
        "near-coin-flip probability). They do not measure real-world outcomes.\n"
    )

    try:
        from groq import Groq

        client = Groq(api_key=api_key)
        completion = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[
                {"role": "system", "content": GROQ_SYSTEM_PROMPT},
                {"role": "user", "content": prompt},
            ],
            temperature=0.3,
            max_tokens=200,
        )
        reasoning = completion.choices[0].message.content.strip()

        # Verify the model honoured the vocabulary constraint. If it slipped a
        # banned term in, the text is not audit-safe, so we discard it and fall
        # back to the deterministic summary rather than publish the claim.
        banned = _banned_terms_in(reasoning)
        if banned:
            logger.warning(
                "Override reasoning contained banned vocabulary %s; using fallback.",
                banned,
            )
            return _fallback_reasoning(verdict, consistency_score, flags)
        return reasoning
    except Exception:  # noqa: BLE001 - any client/network error degrades gracefully
        logger.exception("Groq override-reasoning call failed; using fallback.")
        return _fallback_reasoning(verdict, consistency_score, flags)


def run_judge_agent(
    analyst: AnalystReport, forecast: ForecastReport
) -> JudgeVerdict:
    """Adjudicate a forecast against its analyst report and return a JudgeVerdict.

    Args:
        analyst: The descriptive read of the asset.
        forecast: The predictive call (with confidence interval) to adjudicate.

    Returns:
        A :class:`JudgeVerdict` with the consistency score, flags, an
        LLM-generated justification, and a unique ``audit_id``.
    """
    analyst_prob_up = _analyst_composite_prob(analyst)
    consistency_score = _compute_consistency(
        analyst_prob_up, forecast.direction_probability
    )
    flags = _collect_flags(forecast)
    verdict = _decide_verdict(consistency_score, flags)
    override_reasoning = _generate_override_reasoning(
        verdict, consistency_score, flags
    )

    return JudgeVerdict(
        verdict=verdict,
        consistency_score=consistency_score,
        flags=flags,
        override_reasoning=override_reasoning,
        audit_id=str(uuid.uuid4()),
    )
