"""Judge agent: a supervisory layer that adjudicates the forecast.

The analyst and forecast agents can each be individually plausible yet jointly
incoherent — e.g. the analyst reads bullish technicals while the forecaster
predicts a decline. Acting on contradictory signals is how automated systems
lose money. The judge exists to catch that: it scores the *agreement* between
the descriptive and predictive views, raises risk flags, and renders an
auditable verdict (Approved / Conflicted / Rejected) before anything downstream
acts on the call.

The override reasoning is generated by a Groq-hosted LLM so the audit log
carries a plain-English justification. The call is best-effort: if no API key
is configured or the request fails, we fall back to a deterministic summary so
the pipeline never blocks on an external dependency.
"""

from __future__ import annotations

import logging
import os
import re
import uuid

from backend.ml.models.forecaster import NEUTRAL_BAND
from backend.schemas import (
    AnalystReport,
    ForecastReport,
    JudgeVerdict,
    RagRetrieval,
    RetrievalTier,
    RiskReport,
    RiskTier,
    SentimentReport,
    Verdict,
)

logger = logging.getLogger(__name__)

# A confidence interval wider than this fraction of the [0,1] probability space
# means the two boosters disagree materially — the forecast is not trustworthy.
WIDE_CI_THRESHOLD = 0.3

# Verdict thresholds on the consistency score.
APPROVE_MIN_CONSISTENCY = 0.7
REJECT_MAX_CONSISTENCY = 0.3

# The consistency score has two stages: a *directional* agreement score and a
# *confidence* modifier. They answer different questions:
#
#   1. Directional agreement (analyst + sentiment): do the independent reads
#      point the same WAY as the forecast? These are the only inherently
#      directional signals. Weights must sum to 1 so the score stays in [0, 1].
#        * Analyst (0.6): the heavier corroborator — it reads the same price/
#          fundamental data family as the forecast, so agreement is the most
#          meaningful coherence check.
#        * Sentiment (0.4): a genuinely *independent* signal (news, not price);
#          divergence here is informative.
ANALYST_WEIGHT = 0.6
SENTIMENT_WEIGHT = 0.4

#   2. Confidence modifier (risk): how much should we TRUST the directional call
#      at all? Risk is not directional — elevated volatility doesn't argue up or
#      down, it argues "trust any directional call less". So the risk tier scales
#      the directional score multiplicatively rather than voting on direction.
#      High risk applies a haircut; Low and Medium leave it untouched (Low must
#      not *boost* confidence, only avoid penalising it).
_RISK_TIER_CONFIDENCE_FACTOR = {
    RiskTier.LOW: 1.0,
    RiskTier.MEDIUM: 1.0,
    RiskTier.HIGH: 0.85,
}

GROQ_MODEL = "llama-3.3-70b-versatile"

# The judge adjudicates *internal coherence*, not market correctness. The LLM
# must never imply the forecast is right — it can only describe agreement
# between the two agents and the model's own self-reported uncertainty. This
# prompt hard-constrains the vocabulary to keep the audit log defensible.
GROQ_SYSTEM_PROMPT = (
    "You are a risk-governance judge for an automated equity-analysis system. "
    "You write concise, defensible audit justifications.\n\n"
    "CRITICAL CONSTRAINTS:\n"
    "- You assess ONLY the internal coherence of two software agents: the "
    "analyst agent (which summarises current technical/fundamental signals) and "
    "the forecast agent (which outputs a directional probability). You are NOT "
    "evaluating whether any prediction is or will be true.\n"
    "- The consistency score measures ONLY how much the two agents' signals AGREE "
    "with each other. A high score means they point the same way; it does NOT "
    "mean the forecast is right.\n"
    "- Flags describe ONLY model-internal confidence / data-quality conditions "
    "(e.g. wide confidence interval, near-coin-flip probability), NOT real-world "
    "outcomes.\n"
    "- NEVER claim or imply predictive accuracy, correctness, or real-world "
    "reliability. Do NOT use the words 'accurate', 'accuracy', 'correct', "
    "'reliable', 'reliable performance', 'right', 'proven', or 'validated', nor "
    "any synonym that suggests the prediction will hold true.\n"
    "- The risk tier is a PENALTY-ONLY confidence modifier. A High tier REDUCES "
    "trust in the call. A Low or Medium tier merely AVOIDS a penalty — it does "
    "NOT raise, boost, increase, improve, or strengthen trust or confidence. "
    "NEVER write that low or medium risk increases/boosts/raises confidence or "
    "trust, not even hypothetically ('would normally increase trust'). At most "
    "say it 'does not reduce' or 'leaves trust unchanged'.\n"
    "- DOCUMENT EVIDENCE has three tiers; match your language to the stated tier "
    "exactly. STRONG: you may cite the excerpts by section (e.g. 'Risk Factors') "
    "as support for or contradiction of the forecast direction. MODERATE: refer "
    "to the excerpts only as 'partial' or 'directionally relevant' context — do "
    "NOT present them as solid, strong, or conclusive support, and do NOT call "
    "them insufficient. INSUFFICIENT: write that document evidence was "
    "insufficient and do NOT cite, invent, paraphrase, or imply any specific "
    "filing content. Never claim a tier other than the one given, and never "
    "fabricate evidence you were not shown.\n"
    "- Frame everything as agreement/disagreement between agents and as "
    "model-reported confidence. Describe what was measured, not what will happen."
)

# Post-generation guardrail. The system prompt *asks* the LLM to avoid claiming
# predictive correctness, but a prompt is not a guarantee — so we also *verify*
# the output. Any of these stems implies the forecast is correct or will hold
# true, which the judge must never assert. Matched as stems (case-insensitive)
# so inflections are caught too: 'accura' -> accurate/accuracy/accurately,
# 'reliab' -> reliable/reliably/reliability, 'validat' -> validate/validated.
_BANNED_VOCABULARY = (
    "accura",
    "correct",
    "reliab",
    "proven",
    "validat",
    "right",
)
_BANNED_PATTERN = re.compile(
    r"\b(?:" + "|".join(_BANNED_VOCABULARY) + r")\w*", re.IGNORECASE
)

# Second guardrail: risk is a penalty-only modifier, so the reasoning must never
# say low/medium risk *raises* trust or confidence. We catch an increase-style
# verb aimed at "trust" or "confidence" within a few words (e.g. "increase
# trust", "boosts confidence", "would normally increase trust in the forecast").
# "low confidence"/"reduced confidence" never match — there is no boost verb.
_RISK_BOOST_PATTERN = re.compile(
    r"\b(?:increas\w*|boost\w*|rais\w*|elevat\w*|improv\w*|strengthen\w*|"
    r"heighten\w*|bolster\w*|enhanc\w*)\b(?:\W+\w+){0,3}?\W+(?:trust|confidence)\b",
    re.IGNORECASE,
)


def _banned_terms_in(text: str) -> list[str]:
    """Return any banned-vocabulary matches found in ``text`` (empty if clean)."""
    return [m.group(0) for m in _BANNED_PATTERN.finditer(text)]


def _risk_boost_phrases_in(text: str) -> list[str]:
    """Return any phrases implying risk *boosts* trust/confidence (empty if clean)."""
    return [m.group(0) for m in _RISK_BOOST_PATTERN.finditer(text)]


def _analyst_composite_prob(report: AnalystReport) -> float:
    """Collapse the analyst's technical read into a single bullishness score.

    The analyst report has no scalar verdict of its own, so we synthesise one
    from three orthogonal momentum/positioning signals, each normalised to
    [-1, 1] and averaged, then mapped to a probability-like [0, 1]:

      * RSI relative to its 50 midpoint (momentum),
      * MACD histogram sign (trend acceleration),
      * %B position within the Bollinger envelope (mean-reversion context).

    Expressing it on the same [0, 1] scale as the forecaster's ``probability_up``
    lets us compare the two views directly.
    """
    tech = report.technicals

    rsi_signal = max(-1.0, min(1.0, (tech.rsi - 50.0) / 50.0))
    macd_signal = 1.0 if tech.macd_hist > 0 else (-1.0 if tech.macd_hist < 0 else 0.0)
    bb_signal = max(-1.0, min(1.0, (tech.bb_pct - 0.5) * 2.0))

    composite = (rsi_signal + macd_signal + bb_signal) / 3.0  # [-1, 1]
    return (composite + 1.0) / 2.0  # [0, 1]


def _sentiment_prob_up(report: SentimentReport) -> float:
    """Map the aggregate sentiment polarity [-1, 1] onto a P(up)-like [0, 1]."""
    return (report.sentiment_score + 1.0) / 2.0


def _risk_confidence_factor(report: RiskReport) -> float:
    """Confidence haircut implied by the risk tier (multiplicative, in (0, 1])."""
    return _RISK_TIER_CONFIDENCE_FACTOR[report.risk_tier]


def _agreement(signal_prob_up: float, forecast_prob_up: float) -> float:
    """Directional agreement of one signal with the forecast, in [0, 1].

    Both live on a shared P(up) scale, so their absolute difference is a natural
    disagreement metric: identical convictions score 1.0, opposite ones 0.0.
    """
    return 1.0 - abs(signal_prob_up - forecast_prob_up)


def _compute_consistency(
    analyst_prob_up: float,
    sentiment_prob_up: float,
    forecast_prob_up: float,
    risk_confidence_factor: float,
) -> float:
    """Risk-modulated directional agreement of analyst and sentiment with the forecast.

    Two stages:
      1. Directional agreement — how well the analyst and sentiment reads point
         the same WAY as the forecast, blended with the documented weights
         (analyst 0.6, sentiment 0.4; they sum to 1, so this stays in [0, 1]).
      2. Confidence modifier — the directional score is then scaled by the risk
         tier's factor. Risk informs *how much to trust* the call, not which way
         to lean: a High tier applies a haircut (less trust under elevated
         volatility); Low/Medium leave the score untouched (Low does not boost).

    The product stays in [0, 1] since both stages are in [0, 1].
    """
    directional = (
        ANALYST_WEIGHT * _agreement(analyst_prob_up, forecast_prob_up)
        + SENTIMENT_WEIGHT * _agreement(sentiment_prob_up, forecast_prob_up)
    )
    return directional * risk_confidence_factor


def _collect_flags(forecast: ForecastReport) -> list[str]:
    """Raise qualitative risk flags from the forecast's own uncertainty signals."""
    flags: list[str] = []

    ci_low, ci_high = forecast.confidence_interval
    if (ci_high - ci_low) > WIDE_CI_THRESHOLD:
        flags.append("wide uncertainty")

    # Headline probability sitting inside the neutral band means the model is
    # effectively undecided — a coin-flip dressed up as a directional call.
    if abs(forecast.direction_probability - 0.5) <= NEUTRAL_BAND:
        flags.append("low confidence")

    return flags


def _decide_verdict(consistency_score: float, flags: list[str]) -> Verdict:
    """Map the consistency score and flags onto the three-state verdict.

    Approval demands both high agreement *and* a clean flag sheet; a strong
    consistency score cannot rescue a forecast the model itself flagged as
    uncertain. Low agreement is an outright rejection; everything in between is
    escalated as Conflicted for human review.
    """
    if consistency_score < REJECT_MAX_CONSISTENCY:
        return Verdict.REJECTED
    if consistency_score > APPROVE_MIN_CONSISTENCY and not flags:
        return Verdict.APPROVED
    return Verdict.CONFLICTED


def _fallback_reasoning(
    verdict: Verdict, consistency_score: float, flags: list[str]
) -> str:
    """Deterministic justification used when the LLM call is unavailable."""
    flag_text = ", ".join(flags) if flags else "no risk flags"
    return (
        f"Verdict {verdict.value} was assigned because the analyst and forecast "
        f"directions agree at a consistency of {consistency_score:.2f}, with "
        f"{flag_text}. This decision was generated without the LLM justifier "
        f"(Groq unavailable), so it reflects the rule thresholds directly."
    )


_EVIDENCE_SNIPPET_CHARS = 280
_EVIDENCE_MAX_CHUNKS = 3


def _format_evidence_block(rag: RagRetrieval) -> str:
    """Render the 10-K evidence for the prompt, with language gated by the tier.

    Three regimes, so the model's wording matches the actual match quality:
      * INSUFFICIENT — withhold the snippets entirely and tell the model the
        evidence was insufficient. It cannot cite what it was never shown, which
        structurally prevents fabricated document confidence.
      * MODERATE — pass the snippets but instruct the model to treat them as
        partial / directionally relevant, NOT as solid support.
      * STRONG — pass the snippets and invite confident citation by section.
    """
    if rag.confidence_tier == RetrievalTier.INSUFFICIENT or not rag.evidence_sources:
        return (
            "Document evidence (10-K): INSUFFICIENT. The retrieval returned no "
            f"sufficiently relevant excerpts (top similarity "
            f"{rag.retrieval_confidence:.2f}). State that document evidence was "
            "insufficient; do NOT cite or infer any specific filing content."
        )

    if rag.confidence_tier == RetrievalTier.MODERATE:
        header = (
            f"Document evidence (10-K): MODERATE (top similarity "
            f"{rag.retrieval_confidence:.2f}). Treat the excerpts below as only "
            "PARTIAL / directionally relevant context — describe them as partial "
            "and do NOT present them as solid or conclusive support:"
        )
    else:  # STRONG
        header = (
            f"Document evidence (10-K): STRONG (top similarity "
            f"{rag.retrieval_confidence:.2f}). You may cite these by section as "
            "support for or contradiction of the forecast direction:"
        )

    lines = [header]
    for e in rag.evidence_sources[:_EVIDENCE_MAX_CHUNKS]:
        snippet = " ".join(e.snippet[:_EVIDENCE_SNIPPET_CHARS].split())
        lines.append(f"  - [{e.section}, sim={e.similarity_score:.2f}] {snippet}")
    return "\n".join(lines)


def _generate_override_reasoning(
    verdict: Verdict,
    consistency_score: float,
    flags: list[str],
    risk_tier: str,
    sentiment_label: str,
    evidence_block: str,
) -> str:
    """Ask a Groq-hosted LLM to justify the verdict in 2-3 plain-English sentences.

    Falls back to a deterministic summary when ``GROQ_API_KEY`` is unset or the
    API call fails, so adjudication never depends on network availability.
    """
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        logger.info("GROQ_API_KEY not set; using deterministic override reasoning.")
        return _fallback_reasoning(verdict, consistency_score, flags)

    flag_text = ", ".join(flags) if flags else "none"
    prompt = (
        "Justify the verdict below for a compliance audit log in 2-3 plain-English "
        "sentences. Reference the numbers.\n\n"
        f"Verdict: {verdict.value}\n"
        f"Consistency score: {consistency_score:.2f} — how closely two independent reads "
        "(analyst technicals and news sentiment) AGREE in direction with the forecast "
        "agent's call (1.0 = aligned, 0.0 = opposed), then scaled down when the asset's "
        "risk tier is High (elevated volatility = trust any directional call less). Risk "
        "informs HOW MUCH to trust the forecast, not which way to lean. The score says "
        "nothing about whether the prediction will come true.\n"
        f"Risk tier of the asset: {risk_tier} (a confidence modifier). News sentiment: {sentiment_label}.\n"
        f"Risk flags: {flag_text} — these are confidence / data-quality signals derived "
        "from the model's own internal uncertainty (e.g. wide confidence interval, "
        "near-coin-flip probability). They do not measure real-world outcomes.\n"
        f"{evidence_block}\n"
    )

    try:
        from groq import Groq

        client = Groq(api_key=api_key)
        completion = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[
                {"role": "system", "content": GROQ_SYSTEM_PROMPT},
                {"role": "user", "content": prompt},
            ],
            temperature=0.3,
            max_tokens=200,
        )
        reasoning = completion.choices[0].message.content.strip()

        # Verify the model honoured the prose constraints. If it slipped in a
        # banned correctness term, or implied that low/medium risk *boosts*
        # confidence, the text is not audit-safe — discard it and fall back to
        # the deterministic summary rather than publish the claim.
        banned = _banned_terms_in(reasoning)
        risk_boost = _risk_boost_phrases_in(reasoning)
        if banned or risk_boost:
            logger.warning(
                "Override reasoning rejected (banned=%s, risk-boost=%s); using fallback.",
                banned, risk_boost,
            )
            return _fallback_reasoning(verdict, consistency_score, flags)
        return reasoning
    except Exception:  # noqa: BLE001 - any client/network error degrades gracefully
        logger.exception("Groq override-reasoning call failed; using fallback.")
        return _fallback_reasoning(verdict, consistency_score, flags)


def run_judge_agent(
    analyst: AnalystReport,
    forecast: ForecastReport,
    risk: RiskReport,
    sentiment: SentimentReport,
    rag: RagRetrieval,
) -> JudgeVerdict:
    """Adjudicate a forecast against the analyst, risk, sentiment and RAG reports.

    Args:
        analyst: The descriptive technical/fundamental read of the asset.
        forecast: The predictive call (with confidence interval) to adjudicate.
        risk: The downside/volatility profile (a confidence modifier).
        sentiment: The recent news polarity (an independent directional signal).
        rag: 10-K evidence + retrieval confidence; cited in the reasoning when
            strong, and explicitly called insufficient when weak.

    Returns:
        A :class:`JudgeVerdict` with the consistency score, flags, an
        LLM-generated justification, and a unique ``audit_id``.
    """
    analyst_prob_up = _analyst_composite_prob(analyst)
    consistency_score = _compute_consistency(
        analyst_prob_up=analyst_prob_up,
        sentiment_prob_up=_sentiment_prob_up(sentiment),
        forecast_prob_up=forecast.direction_probability,
        risk_confidence_factor=_risk_confidence_factor(risk),
    )
    flags = _collect_flags(forecast)
    verdict = _decide_verdict(consistency_score, flags)
    override_reasoning = _generate_override_reasoning(
        verdict,
        consistency_score,
        flags,
        risk_tier=risk.risk_tier.value,
        sentiment_label=sentiment.sentiment_label.value,
        evidence_block=_format_evidence_block(rag),
    )

    return JudgeVerdict(
        verdict=verdict,
        consistency_score=consistency_score,
        flags=flags,
        override_reasoning=override_reasoning,
        audit_id=str(uuid.uuid4()),
    )
